### ISSUE TITLE
Allow selectState to take comparator/keySelector for distinctUntilChanged

### ISSUE THREAD

**Issue by PeterSR** [nigrosimone/ng-simple-state#3]
I have a quite big state object and I don't want all my observables to re-fire every time some unrelated part of the state changes. 
In the current `selectState` there is a `distinctUntilChanged` ([docs](https://rxjs.dev/api/index/function/distinctUntilChanged)), but it is sadly not as effective, since without any arguments it would check at object identity which changes in my case as I create copies to keep everything immutable. 

My own workaround was to override the `selectState`:

```typescript
  // eslint-disable-next-line no-unused-vars
  override selectState<K>(
    selectFn?: (state: Readonly<S>) => K,
    comparator?: (previous: K, current: K) => boolean,
  ): Observable<K> {
    return super.selectState(selectFn).pipe(
      distinctUntilChanged(comparator=comparator)
    )
  }
```

(I only needed `comparator` for the time being)

This is okay, but now there is an extra unnecessary `distinctUntilChanged` in the chain.

Would it be possible to add support for something like this?

**Comment by nigrosimone** [comment]
Yep, published into 14.0.7!

https://www.npmjs.com/package/ng-simple-state/v/14.0.7

**Comment by PeterSR** [comment]
Incredible! That was fast - Thank you :smiley:

**Comment by nigrosimone** [comment]
@PeterSR, just a question. I want add an option for define a global "comparator", eg.:

```ts
@NgModule({
  declarations: [AppComponent],
  imports: [
    NgSimpleStateModule.forRoot({
      comparator: (previous, current) => JSON.stringify(previous) === JSON.stringify(current)
    }),
    AppRoutingModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

and also a store unique comparator, eg.:

```ts
@Injectable()
export class CounterStore extends NgSimpleStateBaseStore<CounterState> {
  override storeConfig(): NgSimpleStateStoreConfig {
    return {
      comparator: (previous, current) => JSON.stringify(previous) === JSON.stringify(current)
    }
  }
}
```

in your expirence with my library is useful?

**Comment by PeterSR** [comment]
I think that sounds like a good idea!

Specifically regarding using JSON stringify, my concern will be 1) speed and 2) reordering of keys, but that's probably why you make it customizable. 


Regarding if your library is useful: Yes, very much! We needed something simple for state management that we then later would replace with something like ngrx, but right now I am not even sure we want or need that.

**Comment by nigrosimone** [comment]
Published in https://www.npmjs.com/package/ng-simple-state/v/15.0.2

JSON stringify is just an example, but it is customizable!

Thanks! I use my library in some simple projects and NGRX in some complex objects. But, honestly, my library can handle projects at any scale...

**Comment by PeterSR** [comment]
Thank you!

And that is great to hear :smile:
